### ISSUE TITLE
Support for v0.1.11 tag

### ISSUE THREAD

**Issue by reefland** [tensorchord/cloudnative-pgvecto.rs#7]
I'm trying to get `Immich` and `Cloudnative-pg` to play nicely with `pgvecto.rs`.  My understanding is that Immich requires  `v0.1.11`.

If I try to use `tensorchord/pgvecto-rs:pg14-v0.1.11` it is rejected by cloudnative-pg, I get message:
```
one or more objects failed to apply, reason: 
admission webhook "vcluster.cnpg.io" denied the request:
  Cluster.cluster.cnpg.io "postgres" is invalid:
  [spec.imageName: Invalid value: "tensorchord/pgvecto-rs:pg14-v0.1.11": invalid version tag, spec.imageName: Invalid value: "tensorchord/pgvecto-rs:pg14-v0.1.11": wrong version: version not starting with a semantic version regex (^(\d\.?)+): pg14-v0.1.11]
```

If I try `tensorchord/cloudnative-pgvecto-rs:14.10-v0.1.11`, obviously fails, doesn't exist.

If I try `tensorchord/cloudnative-pgvecto-rs:14.10-v0.1.13` then every seems to work, until I look at Immich logs:
```
[Nest] 7  - 02/05/2024, 6:22:33 PM   ERROR [JobService] Unable to run job handler (facialRecognition/facial-recognition): QueryFailedError: could not find function "vector_out_wrapper" in file "/usr/lib/postgresql/14/lib/vectors.so"
[Nest] 7  - 02/05/2024, 6:22:33 PM   ERROR [JobService] QueryFailedError: could not find function "vector_out_wrapper" in file "/usr/lib/postgresql/14/lib/vectors.so"
    at PostgresQueryRunner.query (/usr/src/app/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:219:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2192:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2031:30)
    at async SelectQueryBuilder.getRawAndEntities (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:684:29)
    at async SelectQueryBuilder.getOne (/usr/src/app/node_modules/typeorm/query-builder/SelectQueryBuilder.js:711:25)
    at async PersonService.handleRecognizeFaces (/usr/src/app/dist/domain/person/person.service.js:287:22)
    at async /usr/src/app/dist/domain/job/job.service.js:116:37
    at async Worker.processJob (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:394:28)
    at async Worker.retryIfFailed (/usr/src/app/node_modules/bullmq/dist/cjs/classes/worker.js:581:24)
[Nest] 7  - 02/05/2024, 6:22:33 PM   ERROR [JobService] Object:
{
  "id": "174de32a-920e-4954-a910-b876845b38ba",
  "deferred": false
}
```

Which as best I can tell is because v0.1.11 is needed.

**Comment by VoVAllen** [comment]
Immich just released a new version which uses pgvecto.rs v0.2, which is more stable than v0.1.11. Can you try using latest immich +v0.2 in your scenario?

**Comment by bo0tzz** [comment]
Actually, Immich's 0.2.0 support isn't out yet but coming (hopefully) soon. For now I recommend using the old version of this repository, which still has the 0.1.11 tag available: https://github.com/bo0tzz/cnpgvecto.rs/pkgs/container/cnpgvecto.rs/156304508?tag=14.10-v0.1.11

**Comment by reefland** [comment]
> Immich just released a new version which uses pgvecto.rs v0.2, which is more stable than v0.1.11. Can you try using latest immich +v0.2 in your scenario?

I'm running `v1.93.3`, I haven't seen anything in the release notes about supporting newer versions.  The existing example docs still reference the `0.1.11` version.

**Comment by reefland** [comment]
> Actually, Immich's 0.2.0 support isn't out yet but coming (hopefully) soon. For now I recommend using the old version of this repository, which still has the 0.1.11 tag available: https://github.com/bo0tzz/cnpgvecto.rs/pkgs/container/cnpgvecto.rs/156304508?tag=14.10-v0.1.11, or just waiting for the next Immich release to start setting things up.

Thanks using that for now,  I'll keep an eye out for v0.2 support.
